/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.Barcode;
import data.DB_Manager;
import data.Debit108;
import data.DebitProtocol;
import data.PrintActionListener;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author THOMAS
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() 
    {
        try { UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); } catch(Exception e) { e.printStackTrace(); }
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        initJTable();
        refreshJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoDescTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        InfoSerialTB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InfoMeridTB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InfoCountTB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        InfoCountSP = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        BarcodeTB = new javax.swing.JTextField();
        BarcodeLBL = new javax.swing.JLabel();
        InfoButton = new javax.swing.JButton();
        PrinterBTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        InfoObsTB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        InfoHolderTB = new javax.swing.JTextField();
        ChargeFrame = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        InfoMeridTB1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        InfoObsTB1 = new javax.swing.JTextField();
        InfoSerialTB1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        InfoCountTB1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        InfoHolderTB1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        RenewBTN = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        BarcodeScanTB = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        InfoDescTA1 = new javax.swing.JTextArea();
        AddChargeBTN = new javax.swing.JButton();
        ChargeQuantitySP = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ChargeTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        ChargeCB = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ChargeHolderTB = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ChargeBTN = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        ChargeDateTB = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        ChargeFilenameTB = new javax.swing.JTextField();
        ChargeFromLBL = new javax.swing.JLabel();
        ChargeFromTB = new javax.swing.JTextField();
        ChargeToLBL = new javax.swing.JLabel();
        ChargeToTB = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ChargePresidentTB = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        ChargeOrderTB = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        ChargeMember1TB = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        ChargeMember2TB = new javax.swing.JTextField();
        ReturnFrame = new javax.swing.JFrame();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        ReturnBTN = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        InfoCountTB3 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        InfoMeridTB3 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        RenewBTN3 = new javax.swing.JButton();
        InfoObsTB3 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        InfoSerialTB3 = new javax.swing.JTextField();
        BarcodeScanTB2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        InfoDescTA3 = new javax.swing.JTextArea();
        ReturnHolderCB = new javax.swing.JComboBox<>();
        ReturnCountTB = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        MaterialsTBL = new javax.swing.JTable();
        MenuBar = new javax.swing.JMenuBar();
        AddMenu = new javax.swing.JMenu();
        RemoveMenu = new javax.swing.JMenu();
        ChargeMenu = new javax.swing.JMenu();
        ReturnMenu = new javax.swing.JMenu();

        InfoFrame.setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ΠΕΡΙΓΡΑΦΗ");

        InfoDescTA.setColumns(20);
        InfoDescTA.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoDescTA.setRows(5);
        jScrollPane1.setViewportView(InfoDescTA);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ΑΡΙΘΜΟΣ ΟΝΟΜΑΤΟΣ");

        InfoSerialTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ΑΡΙΘΜΟΣ ΜΕΡΙΔΑΣ");

        InfoMeridTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("ΜΟΝΑΔΑ ΜΕΤΡΗΣΗΣ");

        InfoCountTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoCountTB.setText("ΤΕΜΑΧΙΑ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("ΠΟΣΟΤΗΤΑ");

        InfoCountSP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoCountSP.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("BARCODE");

        BarcodeTB.setEditable(false);
        BarcodeTB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BarcodeTB.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        BarcodeLBL.setBackground(new java.awt.Color(255, 255, 255));
        BarcodeLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BarcodeLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BarcodeLBL.setOpaque(true);

        InfoButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        InfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoButtonActionPerformed(evt);
            }
        });

        PrinterBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/print.png"))); // NOI18N
        PrinterBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrinterBTNActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("ΠΑΡΑΤΗΡΗΣΕΙΣ");

        InfoObsTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("ΚΑΤΟΧΟΣ");

        InfoHolderTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout InfoFrameLayout = new javax.swing.GroupLayout(InfoFrame.getContentPane());
        InfoFrame.getContentPane().setLayout(InfoFrameLayout);
        InfoFrameLayout.setHorizontalGroup(
            InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InfoFrameLayout.createSequentialGroup()
                        .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BarcodeTB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InfoSerialTB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InfoFrameLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarcodeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InfoFrameLayout.createSequentialGroup()
                                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InfoMeridTB))
                                .addGap(18, 18, 18)
                                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(InfoCountTB)))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PrinterBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InfoCountSP)))
                    .addComponent(InfoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InfoFrameLayout.createSequentialGroup()
                        .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InfoFrameLayout.createSequentialGroup()
                        .addComponent(InfoObsTB, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InfoHolderTB)))
                .addContainerGap())
        );
        InfoFrameLayout.setVerticalGroup(
            InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoObsTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoHolderTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoSerialTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoMeridTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoCountTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoCountSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarcodeTB)
                    .addComponent(PrinterBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(BarcodeLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(InfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ChargeFrame.setTitle("ΧΡΕΩΣΗ ΥΛΙΚΩΝ");
        ChargeFrame.setResizable(false);

        jTabbedPane1.setFocusable(false);

        InfoMeridTB1.setEditable(false);
        InfoMeridTB1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoMeridTB1.setFocusable(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("ΑΡΙΘΜΟΣ ΟΝΟΜΑΤΟΣ");

        InfoObsTB1.setEditable(false);
        InfoObsTB1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoObsTB1.setFocusable(false);

        InfoSerialTB1.setEditable(false);
        InfoSerialTB1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoSerialTB1.setFocusable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("ΜΟΝΑΔΑ ΜΕΤΡΗΣΗΣ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("ΑΡΙΘΜΟΣ ΜΕΡΙΔΑΣ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("ΚΑΤΟΧΟΣ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("ΠΑΡΑΤΗΡΗΣΕΙΣ");

        InfoCountTB1.setEditable(false);
        InfoCountTB1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoCountTB1.setText("ΤΕΜΑΧΙΑ");
        InfoCountTB1.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("<html>Εισάγεται το barcode του υλικού προς χρέωση στο πεδίο αριστερά και πατήστε Enter για να αναζητηθεί στην βάση.</html>");

        InfoHolderTB1.setEditable(false);
        InfoHolderTB1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoHolderTB1.setFocusable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("ΠΟΣΟΤΗΤΑ");

        RenewBTN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        RenewBTN.setText("ΑΝΑΝΕΩΣΗ");
        RenewBTN.setFocusable(false);
        RenewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenewBTNActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("ΠΕΡΙΓΡΑΦΗ");

        BarcodeScanTB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BarcodeScanTB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BarcodeScanTB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BarcodeScanTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarcodeScanTBActionPerformed(evt);
            }
        });
        BarcodeScanTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BarcodeScanTBKeyPressed(evt);
            }
        });

        InfoDescTA1.setEditable(false);
        InfoDescTA1.setColumns(20);
        InfoDescTA1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoDescTA1.setRows(5);
        InfoDescTA1.setFocusable(false);
        jScrollPane2.setViewportView(InfoDescTA1);

        AddChargeBTN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AddChargeBTN.setText("ΠΡΟΣΘΗΚΗ ΣΤΗΝ ΧΡΕΩΣΗ");
        AddChargeBTN.setEnabled(false);
        AddChargeBTN.setFocusable(false);
        AddChargeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddChargeBTNActionPerformed(evt);
            }
        });

        ChargeQuantitySP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ChargeQuantitySP.setModel(new javax.swing.SpinnerNumberModel());
        ChargeQuantitySP.setEnabled(false);
        ChargeQuantitySP.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddChargeBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InfoSerialTB1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 56, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InfoMeridTB1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InfoCountTB1)
                            .addComponent(jLabel10))
                        .addGap(18, 75, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ChargeQuantitySP)))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BarcodeScanTB, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(RenewBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InfoObsTB1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(InfoHolderTB1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BarcodeScanTB)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoObsTB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoHolderTB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChargeQuantitySP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InfoSerialTB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(InfoMeridTB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(InfoCountTB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(RenewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddChargeBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Χρέωση υλικών", jPanel1);

        ChargeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Περιγραφή", "Παρατηρήσεις", "Ποσότητα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ChargeTable.setFocusable(false);
        ChargeTable.setRowSelectionAllowed(false);
        jScrollPane5.setViewportView(ChargeTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Λίστα χρέωσης", jPanel2);

        ChargeCB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ChargeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "108", "ΠΡΩΤΟΚΟΛΛΟ" }));
        ChargeCB.setFocusable(false);
        ChargeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargeCBActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("ΕΠΙΛΟΓΗ ΧΡΕΩΣΤΙΚΟΥ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("ΚΑΤΟΧΟΣ ΧΡΕΩΣΗΣ");

        ChargeHolderTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("<html>Διαλέξτε το είδος του χρεωστικού και συμπληρώστε τα αντίστοιχα πεδία για την ολοκλήρωση της χρέωσης.</html>");

        ChargeBTN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ChargeBTN.setText("ΟΛΟΚΛΗΡΩΣΗ ΧΡΕΩΣΗΣ");
        ChargeBTN.setFocusable(false);
        ChargeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargeBTNActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("ΗΜΕΡΟΜΗΝΙΑ");

        ChargeDateTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("ΟΝΟΜΑ ΑΡΧΕΙΟΥ");

        ChargeFilenameTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        ChargeFromLBL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChargeFromLBL.setText("ΑΠΟ");
        ChargeFromLBL.setFocusable(false);

        ChargeFromTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        ChargeToLBL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChargeToLBL.setText("ΠΡΟΣ");
        ChargeToLBL.setFocusable(false);

        ChargeToTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("ΠΡΟΕΔΡΟΣ");
        jLabel23.setFocusable(false);

        ChargePresidentTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("ΔΙΑΤΑΓΗ");
        jLabel27.setFocusable(false);

        ChargeOrderTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("ΜΕΛΟΣ 1");
        jLabel28.setFocusable(false);

        ChargeMember1TB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("ΜΕΛΟΣ 2");
        jLabel29.setFocusable(false);

        ChargeMember2TB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChargeBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ChargeHolderTB, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ChargeCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ChargeFromLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(ChargeToLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ChargeToTB, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21)
                            .addComponent(ChargeFromTB, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(ChargeDateTB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ChargeFilenameTB)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(ChargePresidentTB, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(0, 256, Short.MAX_VALUE))
                            .addComponent(ChargeOrderTB)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28)
                            .addComponent(ChargeMember1TB, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChargeMember2TB)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChargeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChargeHolderTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ChargeFromLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChargeFromTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ChargeToLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChargeToTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChargePresidentTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChargeOrderTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChargeMember2TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChargeMember1TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChargeDateTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChargeFilenameTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ChargeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Χρεωστικό", jPanel3);

        javax.swing.GroupLayout ChargeFrameLayout = new javax.swing.GroupLayout(ChargeFrame.getContentPane());
        ChargeFrame.getContentPane().setLayout(ChargeFrameLayout);
        ChargeFrameLayout.setHorizontalGroup(
            ChargeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChargeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ChargeFrameLayout.setVerticalGroup(
            ChargeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChargeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ReturnFrame.setTitle("ΕΠΙΣΤΡΟΦΗ ΥΛΙΚΟΥ");
        ReturnFrame.setResizable(false);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("ΑΡΙΘΜΟΣ ΜΕΡΙΔΑΣ");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("ΚΑΤΟΧΟΣ");

        ReturnBTN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ReturnBTN.setText("ΕΠΙΣΤΡΟΦΗ");
        ReturnBTN.setEnabled(false);
        ReturnBTN.setFocusable(false);
        ReturnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBTNActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("ΠΑΡΑΤΗΡΗΣΕΙΣ");

        InfoCountTB3.setEditable(false);
        InfoCountTB3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoCountTB3.setFocusable(false);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("<html>Εισάγεται το barcode του υλικού προς επιστροφή στο πεδίο αριστερά και πατήστε Enter για να αναζητηθεί στην βάση.</html>");

        InfoMeridTB3.setEditable(false);
        InfoMeridTB3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoMeridTB3.setFocusable(false);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("ΠΟΣΟΤΗΤΑ");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("ΑΡΙΘΜΟΣ ΟΝΟΜΑΤΟΣ");

        RenewBTN3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        RenewBTN3.setText("ΑΝΑΝΕΩΣΗ");
        RenewBTN3.setFocusable(false);
        RenewBTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenewBTN3ActionPerformed(evt);
            }
        });

        InfoObsTB3.setEditable(false);
        InfoObsTB3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoObsTB3.setFocusable(false);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("ΠΕΡΙΓΡΑΦΗ");

        InfoSerialTB3.setEditable(false);
        InfoSerialTB3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoSerialTB3.setFocusable(false);

        BarcodeScanTB2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BarcodeScanTB2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BarcodeScanTB2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BarcodeScanTB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarcodeScanTB2ActionPerformed(evt);
            }
        });
        BarcodeScanTB2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BarcodeScanTB2KeyPressed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("ΜΟΝΑΔΑ ΜΕΤΡΗΣΗΣ");

        InfoDescTA3.setEditable(false);
        InfoDescTA3.setColumns(20);
        InfoDescTA3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoDescTA3.setRows(5);
        InfoDescTA3.setFocusable(false);
        jScrollPane6.setViewportView(InfoDescTA3);

        ReturnHolderCB.setEnabled(false);
        ReturnHolderCB.setFocusable(false);
        ReturnHolderCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnHolderCBActionPerformed(evt);
            }
        });

        ReturnCountTB.setEditable(false);

        javax.swing.GroupLayout ReturnFrameLayout = new javax.swing.GroupLayout(ReturnFrame.getContentPane());
        ReturnFrame.getContentPane().setLayout(ReturnFrameLayout);
        ReturnFrameLayout.setHorizontalGroup(
            ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReturnBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReturnFrameLayout.createSequentialGroup()
                        .addGroup(ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InfoSerialTB3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ReturnFrameLayout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addGap(0, 28, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InfoMeridTB3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InfoCountTB3)
                            .addComponent(jLabel40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReturnCountTB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)))
                    .addComponent(jScrollPane6)
                    .addGroup(ReturnFrameLayout.createSequentialGroup()
                        .addComponent(BarcodeScanTB2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(RenewBTN3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ReturnFrameLayout.createSequentialGroup()
                        .addGroup(ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InfoObsTB3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(jLabel35))
                        .addGap(18, 18, 18)
                        .addGroup(ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReturnFrameLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ReturnHolderCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ReturnFrameLayout.setVerticalGroup(
            ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BarcodeScanTB2)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoObsTB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnHolderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel33)
                    .addComponent(jLabel40)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReturnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoSerialTB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoMeridTB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoCountTB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnCountTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RenewBTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReturnBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Warehouse");

        MaterialsTBL.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        MaterialsTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ΑΑ", "Αρ. Μερίδας", "Αρ. Ονόματος", "Περιγραφή", "Μον. Μέτρησης", "Ποσότητα", "Κάτοχος", "Παρατηρήσεις", "Barcode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MaterialsTBL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MaterialsTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaterialsTBLMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(MaterialsTBL);

        AddMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/add.png"))); // NOI18N
        AddMenu.setText("ΠΡΟΣΘΗΚΗ");
        AddMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMenuMouseClicked(evt);
            }
        });
        MenuBar.add(AddMenu);

        RemoveMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/remove.png"))); // NOI18N
        RemoveMenu.setText("ΑΦΑΙΡΕΣΗ");
        RemoveMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveMenuMouseClicked(evt);
            }
        });
        MenuBar.add(RemoveMenu);

        ChargeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/charge.png"))); // NOI18N
        ChargeMenu.setText("ΧΡΕΩΣΗ");
        ChargeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChargeMenuMouseClicked(evt);
            }
        });
        MenuBar.add(ChargeMenu);

        ReturnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/return.png"))); // NOI18N
        ReturnMenu.setText("ΕΠΙΣΤΡΟΦΗ");
        ReturnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnMenuMouseClicked(evt);
            }
        });
        MenuBar.add(ReturnMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMenuMouseClicked
        
        initInfoFrame();
        
        //Init Info Components
        InfoFrame.setTitle("ΠΡΟΣΘΗΚΗ ΥΛΙΚΟΥ");
        InfoButton.setText("ΠΡΟΣΘΗΚΗ");
        InfoDescTA.setText("");
        InfoDescTA.setEditable(true);
        InfoHolderTB.setText("ΑΠΟΘΗΚΗ");
        InfoHolderTB.setEditable(false);
        InfoObsTB.setText("");
        InfoObsTB.setEditable(true);
        InfoSerialTB.setText("");
        InfoSerialTB.setEditable(true);
        InfoMeridTB.setText("");
        InfoMeridTB.setEditable(true);
        InfoCountTB.setText("ΤΕΜΑΧΙΑ");
        InfoCountTB.setEditable(true);
        InfoCountSP.setValue(0);
        ((DefaultEditor) InfoCountSP.getEditor()).getTextField().setEditable(false);
         
        //Generate Barcode
        Barcode bc;
        
        do { bc = new Barcode(); }
        while((int)dbm.Function("COUNT", "materials", "*", "barcode = " + bc.toString()) > 0);

        BarcodeTB.setText(bc.toString());
        BarcodeLBL.setIcon(new ImageIcon(bc.getImg()));
    }//GEN-LAST:event_AddMenuMouseClicked

    private void InfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoButtonActionPerformed
        
        try
        {
            if (InfoButton.getText().equals("ΠΡΟΣΘΗΚΗ"))
            {
                int new_aa = (int) dbm.Function("MAX", "materials", "aa", "") + 1;

                String values = 
                new_aa + ", " + 
                Integer.parseInt(InfoMeridTB.getText()) + ", " +
                "'" + InfoSerialTB.getText() + "', " +
                "'" + InfoDescTA.getText() + "', " +
                "'" + InfoCountTB.getText() + "', " +
                InfoCountSP.getValue() + ", " +
                "'ΑΠΟΘΗΚΗ', " +
                "'" + InfoObsTB.getText() + "', " +
                "'" + BarcodeTB.getText() + "'";

                dbm.Insert("materials", values);
            }
            else
            {
                dbm.Update("materials", "arithMerid", InfoMeridTB.getText(), "barcode = " + BarcodeTB.getText());
                dbm.Update("materials", "arithOnom", "'" + InfoSerialTB.getText() + "'", "barcode = " + BarcodeTB.getText());
                dbm.Update("materials", "perigrafiIdwn", "'" + InfoDescTA.getText() + "'", "barcode = " + BarcodeTB.getText());
                dbm.Update("materials", "monMetr", "'" + InfoCountTB.getText() + "'", "barcode = " + BarcodeTB.getText());
                dbm.Update("materials", "paratiriseis", "'" + InfoObsTB.getText() + "'", "barcode = " + BarcodeTB.getText() + " AND io = '" + InfoHolderTB.getText() + "'");
                if (InfoCountSP.isEnabled())
                    dbm.Update("materials", "posotita", InfoCountSP.getValue().toString(), "barcode = " + BarcodeTB.getText() + " AND io = '" + InfoHolderTB.getText() + "'");
            }
           
            InfoFrame.setVisible(false);    
            refreshJTable();
            JOptionPane.showMessageDialog(this, "Η διαδικασία ολοκληρώθηκε επιτυχώς.", InfoFrame.getTitle(), JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e)
        {
            InfoFrame.setVisible(false);
            
            JOptionPane.showMessageDialog(this, "Προέκυψε σφάλμα κατά την εκτέλεση της διαδικασίας.", InfoFrame.getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_InfoButtonActionPerformed

    private void MaterialsTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaterialsTBLMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) 
        {
            evt.consume();
            
            int row = MaterialsTBL.getSelectedRow();
            
            boolean inWarehouse = MaterialsTBL.getModel().getValueAt(row, 6).toString().equals("ΑΠΟΘΗΚΗ");
            
            initInfoFrame();

            //Init Info Components
            InfoFrame.setTitle("ΕΠΕΞΕΡΓΑΣΙΑ ΥΛΙΚΟΥ");
            InfoButton.setText("ΕΠΕΞΕΡΓΑΣΙΑ");
            InfoDescTA.setText(MaterialsTBL.getModel().getValueAt(row, 3).toString());
            InfoDescTA.setEditable(true);
            InfoHolderTB.setText(MaterialsTBL.getModel().getValueAt(row, 6).toString());
            InfoHolderTB.setEditable(false);
            String tmp;
            try { tmp = MaterialsTBL.getModel().getValueAt(row, 7).toString(); }
            catch(Exception e) { tmp = ""; }
            InfoObsTB.setText(tmp);
            InfoObsTB.setEditable(true);
            InfoSerialTB.setText(MaterialsTBL.getModel().getValueAt(row, 2).toString());
            InfoSerialTB.setEditable(true);
            InfoMeridTB.setText(MaterialsTBL.getModel().getValueAt(row, 1).toString());
            InfoMeridTB.setEditable(true);
            InfoCountTB.setText(MaterialsTBL.getModel().getValueAt(row, 4).toString());
            InfoCountTB.setEditable(true);
            InfoCountSP.setValue(Integer.parseInt(MaterialsTBL.getModel().getValueAt(row, 5).toString()));
            InfoCountSP.setEnabled(inWarehouse);
            ((DefaultEditor) InfoCountSP.getEditor()).getTextField().setEditable(false);
            
            Barcode bc = new Barcode(MaterialsTBL.getModel().getValueAt(row, 8).toString());
            
            BarcodeTB.setText(bc.toString());
            BarcodeLBL.setIcon(new ImageIcon(bc.getImg()));
        }
    }//GEN-LAST:event_MaterialsTBLMouseClicked

    private void RemoveMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMenuMouseClicked
        int row = MaterialsTBL.getSelectedRow();
        
        if (row < 0) 
        {
            JOptionPane.showMessageDialog(this, "Δεν βρέθηκε επιλεγμένη γραμμή της βάσης προς αφαίρεση.", "ΑΦΑΙΡΕΣΗ ΥΛΙΚΟΥ", JOptionPane.WARNING_MESSAGE);
            return;
        } 
        if (!MaterialsTBL.getModel().getValueAt(row, 6).toString().equals("ΑΠΟΘΗΚΗ"))
        {
            JOptionPane.showMessageDialog(this, "Δεν είναι δυνατή η αφαίρεση χρεώσεων αλλά μόνο η επιστροφή τους.", "ΑΦΑΙΡΕΣΗ ΥΛΙΚΟΥ", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if ((int)dbm.Function("COUNT", "materials", "barcode", "barcode = " + MaterialsTBL.getModel().getValueAt(row, 8).toString()) > 1)
        {
            JOptionPane.showMessageDialog(this, "Δεν είναι δυνατή η αφαίρεση υλικών με ενεργές χρεώσεις.", "ΑΦΑΙΡΕΣΗ ΥΛΙΚΟΥ", JOptionPane.WARNING_MESSAGE);
            return;
        }
            
        dbm.Delete("materials", "barcode = " + MaterialsTBL.getModel().getValueAt(row, 8).toString() + " AND io = 'ΑΠΟΘΗΚΗ'");
        dbm.Update("materials", "aa", "aa - 1", "aa > " + MaterialsTBL.getModel().getValueAt(row, 0).toString());
        refreshJTable();
        JOptionPane.showMessageDialog(this, "Η διαδικασία ολοκληρώθηκε επιτυχώς.", "ΑΦΑΙΡΕΣΗ ΥΛΙΚΟΥ", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_RemoveMenuMouseClicked

    private void renewChargeFrame1()
    {
        BarcodeScanTB.setText("");
        BarcodeScanTB.setBackground(Color.WHITE);
        BarcodeScanTB.setEditable(true);
        BarcodeScanTB.setFocusable(true);
        BarcodeScanTB.requestFocus();
        
        InfoDescTA1.setText("");
        InfoObsTB1.setText("");
        InfoHolderTB1.setText("");
        InfoSerialTB1.setText("");
        InfoMeridTB1.setText("");
        InfoCountTB1.setText("");
        
        ChargeQuantitySP.setValue(0);
        ChargeQuantitySP.setEnabled(false);
        AddChargeBTN.setEnabled(false);
    }
    
    private void renewChargeFrame2()
    {
        ChargeCB.setSelectedIndex(0);
        
        ChargeHolderTB.setText("");
        ChargeFromTB.setText("");
        ChargeToTB.setText("");
        ChargeFromTB.setEnabled(true);
        ChargeToTB.setEnabled(true);
        ChargePresidentTB.setEnabled(false);
        ChargePresidentTB.setText("");
        ChargeOrderTB.setEnabled(false);
        ChargeOrderTB.setText("");
        ChargeMember1TB.setEnabled(false);
        ChargeMember1TB.setText("");
        ChargeMember2TB.setEnabled(false);
        ChargeMember2TB.setText("");  
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");  
        DateTimeFormatter dtf2 = DateTimeFormatter.ofPattern("dd_MM_yyyy");  
        
        LocalDateTime now = LocalDateTime.now();  
        ChargeDateTB.setText(dtf.format(now));
        
        ChargeFilenameTB.setText("108-" + dtf2.format(now) + "-" + r.nextInt(99999999) + 1);
    }
    
    private void RenewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenewBTNActionPerformed
        renewChargeFrame1();
    }//GEN-LAST:event_RenewBTNActionPerformed

    private void ChargeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChargeMenuMouseClicked
        initChargeFrame();
    }//GEN-LAST:event_ChargeMenuMouseClicked

    private void BarcodeScanTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarcodeScanTBActionPerformed
        if((int)dbm.Function("COUNT", "materials", "*", "barcode = " + BarcodeScanTB.getText() + " AND io = 'ΑΠΟΘΗΚΗ'") > 0)
        {
            BarcodeScanTB.setBackground(Color.GREEN);
            BarcodeScanTB.setEditable(false);
            BarcodeScanTB.setFocusable(false);
            
            charge_material = dbm.Select("*", "materials", "barcode = " + BarcodeScanTB.getText() + " AND io = 'ΑΠΟΘΗΚΗ'").get(0);
            
            InfoDescTA1.setText(charge_material[3].toString());
            InfoObsTB1.setText(charge_material[7].toString());
            InfoHolderTB1.setText(charge_material[6].toString());
            InfoSerialTB1.setText(charge_material[2].toString());
            InfoMeridTB1.setText(charge_material[1].toString());
            InfoCountTB1.setText(charge_material[4].toString());
            
            int quantity = Integer.parseInt(charge_material[5].toString());
            
            ChargeQuantitySP.setValue(quantity);
            
            if (quantity > 0)
            {
                ChargeQuantitySP.setModel(new SpinnerNumberModel(1, 1, quantity, 1));
                ((DefaultEditor) ChargeQuantitySP.getEditor()).getTextField().setEditable(false);
                ChargeQuantitySP.setEnabled(true);
                AddChargeBTN.setEnabled(true);
            }
        }
        else
        {
            BarcodeScanTB.setBackground(Color.RED);
        }        
        //System.out.println(Arrays.toString(results.get(0)));
    }//GEN-LAST:event_BarcodeScanTBActionPerformed

    private void AddChargeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddChargeBTNActionPerformed
        if(!alreadyInChargeTable())
        {
            ((DefaultTableModel) ChargeTable.getModel()).addRow(new Object[]{charge_material[3], "", ChargeQuantitySP.getValue()});
            charge_materials.add(charge_material);
            resizeJTable(ChargeTable);
        }
        else JOptionPane.showMessageDialog(this, "Το υλικό έχει ήδη προστεθεί στον παρών πίνακα χρεώσεων", "ΧΡΕΩΣΗ ΥΛΙΚΩΝ", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_AddChargeBTNActionPerformed

    private void BarcodeScanTBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BarcodeScanTBKeyPressed
        BarcodeScanTB.setBackground(Color.WHITE);
    }//GEN-LAST:event_BarcodeScanTBKeyPressed

    private void ChargeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChargeBTNActionPerformed
        if (charge_materials.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Δεν έχει προστεθεί κανένα υλικό στον πίνακα χρεώσεων", "ΧΡΕΩΣΗ ΥΛΙΚΩΝ", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        for (int i = 0; i < charge_materials.size(); i++)
        {
            charge_materials.get(i)[5] = ChargeTable.getModel().getValueAt(i, 2);
            charge_materials.get(i)[6] = ChargeHolderTB.getText();
            charge_materials.get(i)[7] = ChargeTable.getModel().getValueAt(i, 1);  
        }
        
        if(ChargeCB.getSelectedItem().toString().equals("108"))
        {
            Debit108 d108 = new Debit108
            (
                ChargeFromTB.getText(),
                ChargeToTB.getText(),
                ChargeDateTB.getText(),
                ChargeFilenameTB.getText(),
                charge_materials
            );
            
            d108.createDocx(); 
        }
        else
        {
            DebitProtocol dProtocol = new DebitProtocol
            (
                ChargePresidentTB.getText(),
                ChargeOrderTB.getText(),
                ChargeMember1TB.getText(),
                ChargeMember2TB.getText(), 
                ChargeDateTB.getText(),
                ChargeFilenameTB.getText(),
                charge_materials
            );
            
            dProtocol.createDocx(); 
        }

        for (int i = 0; i < charge_materials.size(); i++)
        {
            dbm.Update("materials", "posotita", "posotita - " + charge_materials.get(i)[5], "barcode = " + charge_materials.get(i)[8] + " AND io = 'ΑΠΟΘΗΚΗ'");
            
            String values = 
                charge_materials.get(i)[0] + ", " + 
                charge_materials.get(i)[1] + ", " +
                "'" + charge_materials.get(i)[2] + "', " +
                "'" + charge_materials.get(i)[3] + "', " +
                "'" + charge_materials.get(i)[4] + "', " +
                charge_materials.get(i)[5] + ", " +
                "'" + charge_materials.get(i)[6] + "', " +
                "'" + charge_materials.get(i)[7] + "', " +
                "'" + charge_materials.get(i)[8] + "'";
            
            dbm.Insert("materials", values);
            
            refreshJTable();
            ChargeFrame.setVisible(false);
            JOptionPane.showMessageDialog(this, "Η χρέωση των υλικών ολοκληρώθηκε επιτυχώς και δημιουργήθηκε το χρεωστικό με τίλτο '" + ChargeFilenameTB.getText() + "'.", "ΧΡΕΩΣΗ ΥΛΙΚΩΝ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ChargeBTNActionPerformed

    private void ChargeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChargeCBActionPerformed
        ChargeHolderTB.setText("");
        ChargeFromTB.setText("");
        ChargeToTB.setText("");
                
        if(ChargeCB.getSelectedItem().toString().equals("108"))
        {
            ChargeFromLBL.setText("ΑΠΟ");
            ChargeToLBL.setText("ΠΡΟΣ");
            ChargePresidentTB.setEnabled(false);
            ChargePresidentTB.setText("");
            ChargeOrderTB.setEnabled(false);
            ChargeOrderTB.setText("");
            ChargeMember1TB.setEnabled(false);
            ChargeMember1TB.setText("");
            ChargeMember2TB.setEnabled(false);
            ChargeMember2TB.setText("");
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");  
            DateTimeFormatter dtf2 = DateTimeFormatter.ofPattern("dd_MM_yyyy");  
        
            LocalDateTime now = LocalDateTime.now();  
            ChargeDateTB.setText(dtf.format(now));

            ChargeFilenameTB.setText("108-" + dtf2.format(now) + "-" + r.nextInt(99999999) + 1);
        }
        else
        {
            ChargeFromTB.setEnabled(false);
            ChargeToTB.setEnabled(false);
            ChargePresidentTB.setEnabled(true);
            ChargePresidentTB.setText("");
            ChargeOrderTB.setEnabled(true);
            ChargeOrderTB.setText("");
            ChargeMember1TB.setEnabled(true);
            ChargeMember1TB.setText("");
            ChargeMember2TB.setEnabled(true);
            ChargeMember2TB.setText("");
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");  
            DateTimeFormatter dtf2 = DateTimeFormatter.ofPattern("dd_MM_yyyy");  
        
            LocalDateTime now = LocalDateTime.now();  
            ChargeDateTB.setText(dtf.format(now));

            ChargeFilenameTB.setText("Protocol-" + dtf2.format(now) + "-" + r.nextInt(99999999) + 1);
        }
        
    }//GEN-LAST:event_ChargeCBActionPerformed

    private void ReturnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBTNActionPerformed
        dbm.Update("materials", "posotita", "posotita + " + ReturnCountTB.getText(), "barcode = " + BarcodeScanTB2.getText() + " AND io = 'ΑΠΟΘΗΚΗ'");
        dbm.Delete("materials", "barcode = " + BarcodeScanTB2.getText() + " AND io = '" + ReturnHolderCB.getSelectedItem().toString() + "'");
        
        ReturnFrame.setVisible(false);    
        refreshJTable();
        
        JOptionPane.showMessageDialog(this, "Το υλικό επιστράφηκε στην βάση με επιτυχία.", "ΕΠΙΣΤΡΟΦΗ ΥΛΙΚΟΥ", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ReturnBTNActionPerformed

    private void RenewBTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenewBTN3ActionPerformed
        initReturnFrame();
    }//GEN-LAST:event_RenewBTN3ActionPerformed

    private void BarcodeScanTB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarcodeScanTB2ActionPerformed
        if((int)dbm.Function("COUNT", "materials", "*", "barcode = " + BarcodeScanTB2.getText() + " AND io != 'ΑΠΟΘΗΚΗ'") > 0)
        {
            BarcodeScanTB2.setBackground(Color.GREEN);
            BarcodeScanTB2.setEditable(false);
            BarcodeScanTB2.setFocusable(false);
            
            return_materials = dbm.Select("*", "materials", "barcode = " + BarcodeScanTB2.getText() + " AND io != 'ΑΠΟΘΗΚΗ'");
            
            for (int i = 0; i < return_materials.size(); i++) ReturnHolderCB.addItem(return_materials.get(i)[6].toString());
            
            InfoDescTA3.setText(return_materials.get(0)[3].toString());
            InfoObsTB3.setText(return_materials.get(0)[7].toString());
            InfoSerialTB3.setText(return_materials.get(0)[2].toString());
            InfoMeridTB3.setText(return_materials.get(0)[1].toString());
            InfoCountTB3.setText(return_materials.get(0)[4].toString());
            
            ReturnCountTB.setText(return_materials.get(0)[5].toString());
            
            ReturnHolderCB.setEnabled(true);
            ReturnBTN.setEnabled(true);
        }
        else
        {
            BarcodeScanTB2.setBackground(Color.RED);
        }
    }//GEN-LAST:event_BarcodeScanTB2ActionPerformed

    private void BarcodeScanTB2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BarcodeScanTB2KeyPressed
        BarcodeScanTB2.setBackground(Color.WHITE);
    }//GEN-LAST:event_BarcodeScanTB2KeyPressed

    private void ReturnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnMenuMouseClicked
        initReturnFrame();
    }//GEN-LAST:event_ReturnMenuMouseClicked

    private void ReturnHolderCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnHolderCBActionPerformed
        InfoObsTB3.setText(return_materials.get(ReturnHolderCB.getSelectedIndex())[7].toString());
        ReturnCountTB.setText(return_materials.get(ReturnHolderCB.getSelectedIndex())[5].toString());
    }//GEN-LAST:event_ReturnHolderCBActionPerformed

    private void PrinterBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrinterBTNActionPerformed
        ImageIcon imageIcon = (ImageIcon)BarcodeLBL.getIcon();
        
        Image image = imageIcon.getImage();        
        BufferedImage buffered = new BufferedImage(
            imageIcon.getIconWidth(),
            imageIcon.getIconHeight(),
            BufferedImage.TYPE_INT_ARGB
        );
        Graphics2D g = buffered.createGraphics();
        g.drawImage(image, 0, 0, null);
        g.dispose();
        
        new Thread(new PrintActionListener(buffered)).start();
    }//GEN-LAST:event_PrinterBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    private void initJTable()
    {                
        MaterialsTBL.setRowHeight(60);
        MaterialsTBL.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 20));
        MaterialsTBL.getTableHeader().setOpaque(false);
        MaterialsTBL.getTableHeader().setBackground(Color.LIGHT_GRAY);
 
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) MaterialsTBL.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
    }
    
    private void initInfoFrame()
    {
        InfoFrame.setPreferredSize(new Dimension(500, 450));
        InfoFrame.pack();
        InfoFrame.setLocationRelativeTo(null);
        InfoFrame.setVisible(true);
    }
    
    private void initChargeFrame()
    {
        renewChargeFrame1();
        renewChargeFrame2();
        
        ((DefaultTableModel) ChargeTable.getModel()).setRowCount(0);
        charge_materials = new ArrayList<Object[]>();      
        
        ChargeFrame.setPreferredSize(new Dimension(625, 518));
        ChargeFrame.pack();
        ChargeFrame.setLocationRelativeTo(null);
        ChargeFrame.setVisible(true);
    }
    
    private void initReturnFrame()
    {
        BarcodeScanTB2.setText("");
        BarcodeScanTB2.setBackground(Color.WHITE);
        BarcodeScanTB2.setEditable(true);
        BarcodeScanTB2.setFocusable(true);
        BarcodeScanTB2.requestFocus();
        
        InfoDescTA3.setText("");
        InfoObsTB3.setText("");
        
        ReturnHolderCB.setModel(new DefaultComboBoxModel(new String[]{}));
        
        ReturnHolderCB.setEnabled(false);
        InfoSerialTB3.setText("");
        InfoMeridTB3.setText("");
        InfoCountTB3.setText("");
        ReturnCountTB.setText("");
        
        return_materials = new ArrayList<Object[]>();
        
        ReturnBTN.setEnabled(false);
        
        ReturnFrame.setPreferredSize(new Dimension(625, 450));
        ReturnFrame.pack();
        ReturnFrame.setLocationRelativeTo(null);
        ReturnFrame.setVisible(true);
    }
    
    private void refreshJTable()
    {        
        ArrayList<Object[]> selectionList = dbm.Select("*", "materials", "");
        
        Comparator<Object[]> comparator = new Comparator<Object[]>() 
        {
            @Override
            public int compare(Object[] o1, Object[] o2) 
            {
                int aa1 = Integer.parseInt(o1[0].toString());
                int aa2 = Integer.parseInt(o2[0].toString());
                
                if (aa1 < aa2) return -1;
                if (aa1 > aa2) return 1;
                
                String h1 = o1[6].toString();
                String h2 = o2[6].toString();
                
                if (h1.equals("ΑΠΟΘΗΚΗ")) return -1;
                if (h2.equals("ΑΠΟΘΗΚΗ")) return 1;
                
                return h1.compareTo(h2);
            }
        };
        
        Collections.sort(selectionList, comparator);
        
        DefaultTableModel model = (DefaultTableModel) MaterialsTBL.getModel();
        
        int rows = model.getRowCount();
        
        for (int i = 0; i < rows; i++) model.removeRow(0);
        
        for (int i = 0; i < selectionList.size(); i++) 
        {
            model.addRow(selectionList.get(i));
            
            if (!model.getValueAt(i, 6).toString().equals("ΑΠΟΘΗΚΗ")) model.setValueAt("", i, 0);

            
        }
        
        resizeJTable(MaterialsTBL);
    }
    
    private void resizeJTable(JTable table)
    {
        final TableColumnModel columnModel = table.getColumnModel();
        
        for (int column = 0; column < table.getColumnCount(); column++) 
        {
            int width = 15; // Min width
            
            for (int row = 0; row < table.getRowCount(); row++) 
            {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width +1 , width);
            }
            
            if(width > 300) width=300;
            
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }
    
    private boolean alreadyInChargeTable()
    {
        for (int i = 0; i < ChargeTable.getRowCount(); i++) 
            if (charge_material[3].toString().equals(ChargeTable.getModel().getValueAt(i, 0).toString())) return true;
        
        return false;
    }

            
    private Random r = new Random();
    private static DB_Manager dbm = new DB_Manager();
    private static Object[] charge_material;
    private static ArrayList<Object[]> charge_materials = new ArrayList<Object[]>();
    private static ArrayList<Object[]> return_materials = new ArrayList<Object[]>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddChargeBTN;
    private javax.swing.JMenu AddMenu;
    private javax.swing.JLabel BarcodeLBL;
    private javax.swing.JTextField BarcodeScanTB;
    private javax.swing.JTextField BarcodeScanTB2;
    private javax.swing.JTextField BarcodeTB;
    private javax.swing.JButton ChargeBTN;
    private javax.swing.JComboBox<String> ChargeCB;
    private javax.swing.JTextField ChargeDateTB;
    private javax.swing.JTextField ChargeFilenameTB;
    private javax.swing.JFrame ChargeFrame;
    private javax.swing.JLabel ChargeFromLBL;
    private javax.swing.JTextField ChargeFromTB;
    private javax.swing.JTextField ChargeHolderTB;
    private javax.swing.JTextField ChargeMember1TB;
    private javax.swing.JTextField ChargeMember2TB;
    private javax.swing.JMenu ChargeMenu;
    private javax.swing.JTextField ChargeOrderTB;
    private javax.swing.JTextField ChargePresidentTB;
    private javax.swing.JSpinner ChargeQuantitySP;
    private javax.swing.JTable ChargeTable;
    private javax.swing.JLabel ChargeToLBL;
    private javax.swing.JTextField ChargeToTB;
    private javax.swing.JButton InfoButton;
    private javax.swing.JSpinner InfoCountSP;
    private javax.swing.JTextField InfoCountTB;
    private javax.swing.JTextField InfoCountTB1;
    private javax.swing.JTextField InfoCountTB3;
    private javax.swing.JTextArea InfoDescTA;
    private javax.swing.JTextArea InfoDescTA1;
    private javax.swing.JTextArea InfoDescTA3;
    private javax.swing.JFrame InfoFrame;
    private javax.swing.JTextField InfoHolderTB;
    private javax.swing.JTextField InfoHolderTB1;
    private javax.swing.JTextField InfoMeridTB;
    private javax.swing.JTextField InfoMeridTB1;
    private javax.swing.JTextField InfoMeridTB3;
    private javax.swing.JTextField InfoObsTB;
    private javax.swing.JTextField InfoObsTB1;
    private javax.swing.JTextField InfoObsTB3;
    private javax.swing.JTextField InfoSerialTB;
    private javax.swing.JTextField InfoSerialTB1;
    private javax.swing.JTextField InfoSerialTB3;
    private javax.swing.JTable MaterialsTBL;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton PrinterBTN;
    private javax.swing.JMenu RemoveMenu;
    private javax.swing.JButton RenewBTN;
    private javax.swing.JButton RenewBTN3;
    private javax.swing.JButton ReturnBTN;
    private javax.swing.JTextField ReturnCountTB;
    private javax.swing.JFrame ReturnFrame;
    private javax.swing.JComboBox<String> ReturnHolderCB;
    private javax.swing.JMenu ReturnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
