/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.Barcode;
import data.DB_Manager;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author THOMAS
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() 
    {
        try { UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); } catch(Exception e) { e.printStackTrace(); }
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        initJTable();
        refreshJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoDescTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        InfoSerialTB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InfoMeridTB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InfoCountTB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        InfoCountSP = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        BarcodeTB = new javax.swing.JTextField();
        BarcodeLBL = new javax.swing.JLabel();
        InfoButton = new javax.swing.JButton();
        PrinterBTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        InfoObsTB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        InfoHolderTB = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        MaterialsTBL = new javax.swing.JTable();
        MenuBar = new javax.swing.JMenuBar();
        AddMenu = new javax.swing.JMenu();
        RemoveMenu = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        InfoFrame.setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ΠΕΡΙΓΡΑΦΗ");

        InfoDescTA.setColumns(20);
        InfoDescTA.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoDescTA.setRows(5);
        jScrollPane1.setViewportView(InfoDescTA);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ΑΡΙΘΜΟΣ ΟΝΟΜΑΤΟΣ");

        InfoSerialTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ΑΡΙΘΜΟΣ ΜΕΡΙΔΑΣ");

        InfoMeridTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("ΜΟΝΑΔΑ ΜΕΤΡΗΣΗΣ");

        InfoCountTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoCountTB.setText("ΤΕΜΑΧΙΑ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("ΠΟΣΟΤΗΤΑ");

        InfoCountSP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        InfoCountSP.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("BARCODE");

        BarcodeTB.setEditable(false);
        BarcodeTB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BarcodeTB.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        BarcodeLBL.setBackground(new java.awt.Color(255, 255, 255));
        BarcodeLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BarcodeLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BarcodeLBL.setOpaque(true);

        InfoButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        InfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoButtonActionPerformed(evt);
            }
        });

        PrinterBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("ΠΑΡΑΤΗΡΗΣΕΙΣ");

        InfoObsTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("ΚΑΤΟΧΟΣ");

        InfoHolderTB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout InfoFrameLayout = new javax.swing.GroupLayout(InfoFrame.getContentPane());
        InfoFrame.getContentPane().setLayout(InfoFrameLayout);
        InfoFrameLayout.setHorizontalGroup(
            InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InfoFrameLayout.createSequentialGroup()
                        .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BarcodeTB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InfoSerialTB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InfoFrameLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarcodeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InfoFrameLayout.createSequentialGroup()
                                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InfoMeridTB))
                                .addGap(18, 18, 18)
                                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(InfoCountTB)))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PrinterBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InfoCountSP)))
                    .addComponent(InfoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InfoFrameLayout.createSequentialGroup()
                        .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InfoFrameLayout.createSequentialGroup()
                        .addComponent(InfoObsTB, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InfoHolderTB)))
                .addContainerGap())
        );
        InfoFrameLayout.setVerticalGroup(
            InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoObsTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoHolderTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoSerialTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoMeridTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoCountTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoCountSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BarcodeLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BarcodeTB)
                    .addComponent(PrinterBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Warehouse");

        MaterialsTBL.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        MaterialsTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ΑΑ", "Αρ. Μερίδας", "Αρ. Ονόματος", "Περιγραφή", "Μον. Μέτρησης", "Ποσότητα", "Κάτοχος", "Παρατηρήσεις", "Barcode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MaterialsTBL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MaterialsTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaterialsTBLMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(MaterialsTBL);

        AddMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        AddMenu.setText("ΠΡΟΣΘΗΚΗ");
        AddMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMenuMouseClicked(evt);
            }
        });
        MenuBar.add(AddMenu);

        RemoveMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/remove.png"))); // NOI18N
        RemoveMenu.setText("ΑΦΑΙΡΕΣΗ");
        RemoveMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveMenuMouseClicked(evt);
            }
        });
        MenuBar.add(RemoveMenu);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/charge.png"))); // NOI18N
        jMenu3.setText("ΧΡΕΩΣΗ");
        MenuBar.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        jMenu4.setText("ΕΠΙΣΤΡΟΦΗ");
        MenuBar.add(jMenu4);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMenuMouseClicked
        
        initInfoFrame();
        
        //Init Info Components
        InfoFrame.setTitle("ΠΡΟΣΘΗΚΗ ΥΛΙΚΟΥ");
        InfoButton.setText("ΠΡΟΣΘΗΚΗ");
        InfoDescTA.setText("");
        InfoDescTA.setEditable(true);
        InfoHolderTB.setText("ΑΠΟΘΗΚΗ");
        InfoHolderTB.setEditable(false);
        InfoObsTB.setText("");
        InfoObsTB.setEditable(true);
        InfoSerialTB.setText("");
        InfoSerialTB.setEditable(true);
        InfoMeridTB.setText("");
        InfoMeridTB.setEditable(true);
        InfoCountTB.setText("ΤΕΜΑΧΙΑ");
        InfoCountTB.setEditable(true);
        InfoCountSP.setValue(0);
        ((DefaultEditor) InfoCountSP.getEditor()).getTextField().setEditable(false);
         
        //Generate Barcode
        Barcode bc;
        
        do { bc = new Barcode(); }
        while((int)dbm.Function("COUNT", "materials", "*", "barcode = " + bc.toString()) > 0);

        BarcodeTB.setText(bc.toString());
        BarcodeLBL.setIcon(new ImageIcon(bc.getImg()));
    }//GEN-LAST:event_AddMenuMouseClicked

    private void InfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoButtonActionPerformed
        
        try
        {
            if (InfoButton.getText().equals("ΠΡΟΣΘΗΚΗ"))
            {
                int new_aa = (int) dbm.Function("MAX", "materials", "aa", "") + 1;

                String values = 
                new_aa + ", " + 
                Integer.parseInt(InfoMeridTB.getText()) + ", " +
                "'" + InfoSerialTB.getText() + "', " +
                "'" + InfoDescTA.getText() + "', " +
                "'" + InfoCountTB.getText() + "', " +
                InfoCountSP.getValue() + ", " +
                "'ΑΠΟΘΗΚΗ', " +
                "'" + InfoObsTB.getText() + "', " +
                "'" + BarcodeTB.getText() + "'";

                dbm.Insert("materials", values);
            }
            else
            {
                dbm.Update("materials", "arithMerid", InfoMeridTB.getText(), "barcode = " + BarcodeTB.getText());
                dbm.Update("materials", "arithOnom", "'" + InfoSerialTB.getText() + "'", "barcode = " + BarcodeTB.getText());
                dbm.Update("materials", "perigrafiIdwn", "'" + InfoDescTA.getText() + "'", "barcode = " + BarcodeTB.getText());
                dbm.Update("materials", "monMetr", "'" + InfoCountTB.getText() + "'", "barcode = " + BarcodeTB.getText());
                dbm.Update("materials", "paratiriseis", "'" + InfoObsTB.getText() + "'", "barcode = " + BarcodeTB.getText() + " AND io = '" + InfoHolderTB.getText() + "'");
                if (InfoCountSP.isEnabled())
                    dbm.Update("materials", "posotita", InfoCountSP.getValue().toString(), "barcode = " + BarcodeTB.getText() + " AND io = '" + InfoHolderTB.getText() + "'");
            }
           
            InfoFrame.setVisible(false);    
            refreshJTable();
            JOptionPane.showMessageDialog(this, "Η διαδικασία ολοκληρώθηκε επιτυχώς.", InfoFrame.getTitle(), JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e)
        {
            InfoFrame.setVisible(false);
            
            JOptionPane.showMessageDialog(this, "Προέκυψε σφάλμα κατά την εκτέλεση της διαδικασίας.", InfoFrame.getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_InfoButtonActionPerformed

    private void MaterialsTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaterialsTBLMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) 
        {
            evt.consume();
            
            int row = MaterialsTBL.getSelectedRow();
            
            boolean inWarehouse = MaterialsTBL.getModel().getValueAt(row, 6).toString().equals("ΑΠΟΘΗΚΗ");
            
            initInfoFrame();

            //Init Info Components
            InfoFrame.setTitle("ΕΠΕΞΕΡΓΑΣΙΑ ΥΛΙΚΟΥ");
            InfoButton.setText("ΕΠΕΞΕΡΓΑΣΙΑ");
            InfoDescTA.setText(MaterialsTBL.getModel().getValueAt(row, 3).toString());
            InfoDescTA.setEditable(true);
            InfoHolderTB.setText(MaterialsTBL.getModel().getValueAt(row, 6).toString());
            InfoHolderTB.setEditable(false);
            String tmp;
            try { tmp = MaterialsTBL.getModel().getValueAt(row, 7).toString(); }
            catch(Exception e) { tmp = ""; }
            InfoObsTB.setText(tmp);
            InfoObsTB.setEditable(true);
            InfoSerialTB.setText(MaterialsTBL.getModel().getValueAt(row, 2).toString());
            InfoSerialTB.setEditable(true);
            InfoMeridTB.setText(MaterialsTBL.getModel().getValueAt(row, 1).toString());
            InfoMeridTB.setEditable(true);
            InfoCountTB.setText(MaterialsTBL.getModel().getValueAt(row, 4).toString());
            InfoCountTB.setEditable(true);
            InfoCountSP.setValue(Integer.parseInt(MaterialsTBL.getModel().getValueAt(row, 5).toString()));
            InfoCountSP.setEnabled(inWarehouse);
            ((DefaultEditor) InfoCountSP.getEditor()).getTextField().setEditable(false);
            
            Barcode bc = new Barcode(MaterialsTBL.getModel().getValueAt(row, 8).toString());
            
            BarcodeTB.setText(bc.toString());
            BarcodeLBL.setIcon(new ImageIcon(bc.getImg()));
        }
    }//GEN-LAST:event_MaterialsTBLMouseClicked

    private void RemoveMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMenuMouseClicked
        int row = MaterialsTBL.getSelectedRow();
        
        if (row < 0) 
        {
            JOptionPane.showMessageDialog(this, "Δεν βρέθηκε επιλεγμένη γραμμή της βάσης προς αφαίρεση.", "ΑΦΑΙΡΕΣΗ ΥΛΙΚΟΥ", JOptionPane.WARNING_MESSAGE);
            return;
        } 
        if (!MaterialsTBL.getModel().getValueAt(row, 6).toString().equals("ΑΠΟΘΗΚΗ"))
        {
            JOptionPane.showMessageDialog(this, "Δεν είναι δυνατή η αφαίρεση χρεώσεων αλλά μόνο η επιστροφή τους.", "ΑΦΑΙΡΕΣΗ ΥΛΙΚΟΥ", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if ((int)dbm.Function("COUNT", "materials", "barcode", "barcode = " + MaterialsTBL.getModel().getValueAt(row, 8).toString()) > 1)
        {
            JOptionPane.showMessageDialog(this, "Δεν είναι δυνατή η αφαίρεση υλικών με ενεργές χρεώσεις.", "ΑΦΑΙΡΕΣΗ ΥΛΙΚΟΥ", JOptionPane.WARNING_MESSAGE);
            return;
        }
            
        dbm.Delete("materials", "barcode = " + MaterialsTBL.getModel().getValueAt(row, 8).toString() + " AND io = 'ΑΠΟΘΗΚΗ'");
        dbm.Update("materials", "aa", "aa - 1", "aa > " + MaterialsTBL.getModel().getValueAt(row, 0).toString());
        refreshJTable();
        JOptionPane.showMessageDialog(this, "Η διαδικασία ολοκληρώθηκε επιτυχώς.", "ΑΦΑΙΡΕΣΗ ΥΛΙΚΟΥ", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_RemoveMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    private void initJTable()
    {                
        MaterialsTBL.setRowHeight(60);
        MaterialsTBL.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 20));
        MaterialsTBL.getTableHeader().setOpaque(false);
        MaterialsTBL.getTableHeader().setBackground(Color.LIGHT_GRAY);
 
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) MaterialsTBL.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
    }
    
    private void initInfoFrame()
    {
        InfoFrame.setPreferredSize(new Dimension(500, 427));
        InfoFrame.pack();
        InfoFrame.setLocationRelativeTo(null);
        InfoFrame.setVisible(true);
    }
    
    private void refreshJTable()
    {        
        ArrayList<Object[]> selectionList = dbm.Select("*", "materials", "");
        
        DefaultTableModel model = (DefaultTableModel) MaterialsTBL.getModel();
        
        int rows = model.getRowCount();
        
        for (int i = 0; i < rows; i++) model.removeRow(0);
        
        for (int i = 0; i < selectionList.size(); i++) model.addRow(selectionList.get(i));
        
        resizeJTable();
    }
    
    private void resizeJTable()
    {
        final TableColumnModel columnModel = MaterialsTBL.getColumnModel();
        
        for (int column = 0; column < MaterialsTBL.getColumnCount(); column++) 
        {
            int width = 15; // Min width
            
            for (int row = 0; row < MaterialsTBL.getRowCount(); row++) 
            {
                TableCellRenderer renderer = MaterialsTBL.getCellRenderer(row, column);
                Component comp = MaterialsTBL.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width +1 , width);
            }
            
            if(width > 300) width=300;
            
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }

    private static DB_Manager dbm = new DB_Manager();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AddMenu;
    private javax.swing.JLabel BarcodeLBL;
    private javax.swing.JTextField BarcodeTB;
    private javax.swing.JButton InfoButton;
    private javax.swing.JSpinner InfoCountSP;
    private javax.swing.JTextField InfoCountTB;
    private javax.swing.JTextArea InfoDescTA;
    private javax.swing.JFrame InfoFrame;
    private javax.swing.JTextField InfoHolderTB;
    private javax.swing.JTextField InfoMeridTB;
    private javax.swing.JTextField InfoObsTB;
    private javax.swing.JTextField InfoSerialTB;
    private javax.swing.JTable MaterialsTBL;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton PrinterBTN;
    private javax.swing.JMenu RemoveMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
